/**
 * Blueprint composer: playground.config.mjs -> a full Playground blueprint,
 * written (with its staged runtime assets) into <plugin>/.playground/.
 *
 * Composition runs on every launch — it is a cheap JSON build — so the
 * generated blueprint and staged mu-plugins always match the checked-out
 * source. Warm boots skip the blueprint but still need the staged files: the
 * site's mu-plugin symlinks point into the mount at .playground/mu-plugins/.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { wpVersionFor } from '../config.mjs';
import * as steps from './steps.mjs';

/** Package-root assets directory (mu-plugins, default seed data). */
const ASSETS_DIR = fileURLToPath(new URL('../../assets', import.meta.url));

/** Mode -> tagline + landing-page defaults. */
const MODE_DEFAULTS = {
	development: { tagline: 'Development by Krokedil', landing: null },
	demo: { tagline: 'Demo by Krokedil', landing: '/wp-admin/plugins.php' },
	e2e: { tagline: 'E2E by Krokedil', landing: '/wp-admin/plugins.php' },
};

/**
 * The staged mu-plugin basenames for a mode: the proxy-url helper always, the
 * declarative seeder for development, plus the plugin's own files.
 *
 * @param {Object} config Normalized plugin config.
 * @param {string} mode   Blueprint mode.
 * @return {{ name: string, source: string }[]} Basename + absolute source path.
 */
function muPluginFiles(config, mode) {
	const files = [
		{
			name: 'playground-proxy-url.php',
			source: path.join(
				ASSETS_DIR,
				'mu-plugins',
				'playground-proxy-url.php'
			),
		},
	];
	if (mode === 'development' && config.woocommerce) {
		files.push({
			name: 'playground-seeder.php',
			source: path.join(
				ASSETS_DIR,
				'mu-plugins',
				'playground-seeder.php'
			),
		});
		// The [krokedil_dev_orders] test-orders panel; inert unless a page
		// uses the shortcode (prefill wired via krokedil_pg_dev_panel_prefill).
		files.push({
			name: 'dev-orders-panel.php',
			source: path.join(ASSETS_DIR, 'mu-plugins', 'dev-orders-panel.php'),
		});
	}
	for (const rel of config.muPlugins[mode] ?? []) {
		files.push({ name: path.basename(rel), source: rel });
	}
	return files;
}

/**
 * Compose the blueprint object for a mode. Pure: no filesystem access.
 *
 * @param {Object} config Normalized plugin config.
 * @param {string} mode   'development' | 'demo' | 'e2e'.
 * @return {Object} The blueprint JSON object.
 */
export function composeBlueprint(config, mode) {
	const defaults = MODE_DEFAULTS[mode];
	if (!defaults) {
		throw new Error(
			`composeBlueprint: unknown mode "${mode}" (use development, demo or e2e).`
		);
	}
	const development = mode === 'development';

	const list = [];
	if (development || mode === 'demo') {
		list.push(steps.debugConsts(development));
	}
	list.push(steps.reset(development));
	list.push(steps.removeDefaultPlugins());
	list.push(...steps.storefrontTheme());
	list.push(steps.siteIdentity(config, defaults.tagline));
	list.push(steps.flushRewrite());

	if (config.woocommerce) {
		list.push(...steps.wooCommerceBaseline(config.store));
		if (development) {
			list.push(steps.bacsGateway());
		}
		list.push(...steps.wooCommercePages());
		if (mode === 'demo') {
			list.push(...steps.demoStoreConfig(config.store));
		}
	}

	if (development) {
		list.push(...steps.debugPlugins());
	}

	list.push(...steps.activatePlugins(config.activate));

	const options = steps.pluginOptions(config.options[mode] ?? {});
	if (options) {
		list.push(options);
	}

	list.push(steps.dismissWelcomeGuides());

	for (const page of config.pages[mode] ?? []) {
		list.push(steps.createPage(page));
	}

	const muFiles = muPluginFiles(config, mode);
	list.push(
		...steps.linkMuPlugins(
			config.slug,
			muFiles.map((f) => f.name)
		)
	);

	if (development && config.woocommerce) {
		list.push(steps.seedInvocation(config.slug));
	} else if (config.woocommerce && config.demoFixture) {
		list.push(...steps.demoFixture());
	}

	list.push(...(config.extraSteps[mode] ?? []));

	return {
		$schema: 'https://playground.wordpress.net/blueprint-schema.json',
		description: `Generated by @krokedil/wp-playground-tools for ${config.slug} (${mode}).`,
		preferredVersions: {
			php: config.php,
			wp: wpVersionFor(config.wp, mode),
		},
		landingPage: defaults.landing ?? config.landingPage,
		login: true,
		steps: list,
	};
}

/**
 * Compose a mode's blueprint and stage its runtime assets under
 * <root>/.playground/. Idempotent; overwrites previous output.
 *
 * @param {string} root   Plugin root (absolute).
 * @param {Object} config Normalized plugin config.
 * @param {string} mode   Blueprint mode.
 * @return {{ blueprintPath: string }} Path of the written blueprint file.
 */
export function composeAndStage(root, config, mode) {
	const stagingDir = path.join(root, '.playground');
	const muDir = path.join(stagingDir, 'mu-plugins');
	fs.mkdirSync(muDir, { recursive: true });

	// Stage mu-plugins: package assets by absolute path, plugin files relative
	// to the plugin root.
	for (const file of muPluginFiles(config, mode)) {
		const source = path.isAbsolute(file.source)
			? file.source
			: path.join(root, file.source);
		if (!fs.existsSync(source)) {
			throw new Error(
				`playground: mu-plugin not found: ${source} (check config.muPlugins).`
			);
		}
		fs.copyFileSync(source, path.join(muDir, file.name));
	}

	// Stage the seed data for the development seeder.
	if (config.woocommerce) {
		const seedSource = config.seedData
			? path.join(root, config.seedData)
			: path.join(ASSETS_DIR, 'seed-data', 'default.json');
		if (!fs.existsSync(seedSource)) {
			throw new Error(
				`playground: seed data not found: ${seedSource} (check config.seedData).`
			);
		}
		fs.copyFileSync(seedSource, path.join(stagingDir, 'seed-data.json'));
	}

	const blueprint = composeBlueprint(config, mode);
	const blueprintPath = path.join(stagingDir, `blueprint.${mode}.json`);
	fs.writeFileSync(blueprintPath, JSON.stringify(blueprint, null, 2) + '\n');

	return { blueprintPath };
}
